### ISSUE TITLE
Criar uma tela para o usuário escolher qual instância reproduzir

### ISSUE THREAD

**Issue by fernandocandrade** [ONSBR/Plataforma-Executor#5]
Criar uma tela para o usuário escolher qual instância reproduzir

**Comment by hugomenezes** [comment]
- [ ] Conferir se a transferência está sendo persistida na base.
- [ ] Criar tela de transferência.
- [ ] Exibir as transferências cadastradas na base.
- [ ] Carregar os combos de conta a partir da base.
- [ ] Exibir contas na tela de contas obtidas da base.
- [ ] Exibir uma tabela com as reproduções na tela de transferência.
- [ ] Criar serviço para reprodução.(js) Criar registro de reprodução.
- [ ] Tela de comparação de json.
- [ ] Serviço para obter json da instância de processo(lista da memória de processamento).

**Comment by fernandocandrade** [comment]
Foi adicionado nas próprias telas de cadastro de conta e transferência um botão para reprodução a transação que gerou o dado.
